### ISSUE TITLE
What i need add to my map? (broken UI)

### ISSUE THREAD

**Issue by Manmellon** [bretonium/my-infclass-server#10]
Other maps work good, but not my...
![bug_1](https://user-images.githubusercontent.com/24492231/69747763-02ccec80-1158-11ea-897f-a6ac44e7437d.png)
![bug_2](https://user-images.githubusercontent.com/24492231/69747764-02ccec80-1158-11ea-9a39-81e86e453794.png)

**Comment by Kaffeine** [comment]
You have to use [teeuniverse](https://github.com/teeuniverse/teeuniverse) editor to create infclass-compatible maps.

**Comment by Manmellon** [comment]
Well, but all work good(like spawns and other), and this UI too, maybe i can fix it in simple editor

**Comment by Kaffeine** [comment]
The class selector is a part of the map generated by the Infclass Server.
You seem to capture the generated map layer, but it won't work right (as you already noticed).

**Comment by TheVayt** [comment]
Delete '#Generated' group and all envelopes.
Also server should reconvert client map, to do so just clear 'userdir/teeworlds/clientmaps'.

**Comment by Manmellon** [comment]
Well, deleting Generated group didnt help, and cleaning dir too. But i can use teeuniverse now, so i will close it.
