### ISSUE TITLE
Double kill execution on becoming a boomer

### ISSUE THREAD

**Issue by bretonium** [bretonium/my-infclass-server#23]
Sometimes 

Steps to reproduce:
0. This bug does not happen every time
1. 2+ players, one smoker, one human, for example, medic (can be any other class)
2. Human hammers with a very high rate
3. Smoker kills human by hooking and reducing human's health to 0
4. When health becomes 0, human dies and random sets human's class to boomer

Expected:
5. Human quietly dies

Actual:
5. Human's tee explodes. The explosion can infect other humans.

There is another set of steps that leads to the bug. It reproduces even less often than with steps above:
1. 1 solder
2. Soldier places bombs near them and explodes them with very high rate
3. At some moment the bombs reduce soldier's health to 0
4. When health becomes 0, soldier dies and random sets soldier's class to boomer

The consequences of the bug in this case are even worse, because ex-soldier can infect humans in the vicinity without any zombies.

**Comment by bretonium** [comment]
Kudonix told me in the chat that the problem was likely introduced in c06579a2, ./src/game/server/gamemodes/mod.cpp:698. I cannot look into it now, so i will just leave it here for now

**Comment by bretonium** [comment]
the issue is probably fix, but i will leave it open until we verify it

**Comment by Kaffeine** [comment]
The commit 8cf5c1362f5b2a86263e57ea3a258e74ccfb0241 does two things: 
1. It reorders calls thus `CCharacter::Die()` now called before `CCharacter::Infect()`
2. It removes (probably unwanted) `CCharacter::Infect()` call from OnCharacterDeath() that I (by a mistake) introduced in c06579a2cc59f51eec927678c48ff0b83e650234. I thought that it's OK to call Infect() on character death if the killer is a zombie and the victum is a human. I thought that there are cases when a zombie cause CharacterDeath without dealing a damage. Probably this is the case for a zombie hooking a human to death tile. I had no time to double check that.

**Comment by TheVayt** [comment]
I didn't think about that
Yes, hooking a human to death tile now doesn't count as killing and doesn't give zombie any points

**Comment by bretonium** [comment]
Although the issue is fixed in master now, another issue appeared. Now, sometimes, the points to zombies for killing humans are not added

**Comment by Kaffeine** [comment]
Probably fixed by https://github.com/bretonium/my-infclass-server/pull/27 but further testing is needed.

**Comment by bretonium** [comment]
fixed indeed
