### ISSUE TITLE
Extra zombie appears when 4th player joins

### ISSUE THREAD

**Issue by bretonium** [bretonium/my-infclass-server#28]
Steps to reproduce:

1. 3 players in the game, round has already started and player-1 is zombie, player-2 and player-3 are humans.
2. Player-4 joins either from spectators or connects to the server

Expected:
Player-4 is zombie, 2 humans are not affected

Actual:
Player-4 becomes zombie and player-2 becomes zombie

Notes:
It happens in ~50% cases. It happens only when the fourth player joins, and not when fith or further players join.

**Comment by Kaffeine** [comment]
Hey, I bet I already tried to reproduce the issue with those steps!
