### ISSUE TITLE
Merging latin and cyrillic alphabets to stop nickname spoofing

### ISSUE THREAD

**Issue by NewRedsquare** [bretonium/my-infclass-server#38]
Hello,

Some players have fun with copying others' nicknames by using cyrillic characters or similar letters ( small L and capital i ). 

We should maybe forbid cyrillic characters or make the correspondace between them : latin `i` and cyrillic `і` for example. 

I hope you understood the issue 👍

**Comment by bretonium** [comment]
I don't think that nickname spoofing is a problem, or even that there should be expectation of nickname uniqueness. Do not use teeworlds/infclass chat for anything that might require authentication.
