### ISSUE TITLE
Floating hero flag

### ISSUE THREAD

**Issue by Kruimeldief** [bretonium/my-infclass-server#40]
Not sure why or how, so here are two screenshots. Maybe I'm just not aware of a feature that allows flag spawning in the air at specific locations?

![floating-hero-flag-1](https://user-images.githubusercontent.com/55532712/82836916-e8d25380-9ec7-11ea-8498-0021f9669e34.png)
![floating-hero-flag-2](https://user-images.githubusercontent.com/55532712/82836915-e7a12680-9ec7-11ea-90bc-8616e5537a91.png)

**Comment by Kaffeine** [comment]
The possible flag positions are manually set on the map by the map creator (I don't have a editor build to open the map and check if this point is actually added to the map, but it is much likely answer than a bug in the server code).
